<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
$scriptString = '
    var LOCALE = \'' . /* @noEscape */ $block->escapeJs($localeFormatter->getLocaleJs()) .'\';
    var BASE_URL = \'' . /* @noEscape */ $block->escapeJs($block->getBaseUrl()) .'\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->escapeJs($block->getViewFileUrl('/')) . '\'
    };';

echo /* @noEscape */ str_replace('<script', '<script data-cfasync="false"',$secureRenderer->renderTag('script', [], $scriptString, false));
